In [ ]:
1. Write a Python Program to Add Two Matrices?
2. Write a Python Program to Multiply Two Matrices?
3. Write a Python Program to Transpose a Matrix?
4. Write a Python Program to Sort Words in Alphabetic Order?
5. Write a Python Program to Remove Punctuation From a String?

In [9]:
mat1=[[1,2,3]]*3
mat2=[[1,2,3]]*3
matt=[[0,0,0]]*3
for i in range(3):
    for j in range(3):
        matt[i][j]=mat1[i][j]+mat2[i][j]
        
print(matt)

[[2, 4, 6], [2, 4, 6], [2, 4, 6]]


# 2. Write a Python Program to Multiply Two Matrices?

In [10]:
mat1=[[1,2,3]]*3
mat2=[[1,2,3]]*3
matt=[[0,0,0]]*3
for i in range(3):
    for j in range(3):
        matt[i][j]=mat1[i][j]*mat2[i][j]
        
print(matt)

[[1, 4, 9], [1, 4, 9], [1, 4, 9]]


# 3. Write a Python Program to Transpose a Matrix?

In [25]:
import numpy
mat1=[[1,2,3]]*3

print(mat1)

print(numpy.transpose(mat1))





[[1, 2, 3], [1, 2, 3], [1, 2, 3]]
[[1 1 1]
 [2 2 2]
 [3 3 3]]


# 4. Write a Python Program to Sort Words in Alphabetic Order?

In [12]:
s=['abc','ghi','def']
s.sort()
print(s)

['abc', 'def', 'ghi']


# 5. Write a Python Program to Remove Punctuation From a String?

In [26]:
s="Devansh's ? is very good at playing cricket , his favourite shot is Virat's stright mid on drive"
punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''
for i in s:
    if i in punctuations:
        s=s.replace(i,'')
print(s)

Devanshs  is very good at playing cricket  his favourite shot is Virats stright mid on drive
